apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tracon-node
subjects:
  - kind: ServiceAccount
    name: tracon-node
roleRef:
  kind: Role
  name: tracon-node
  apiGroup: rbac.authorization.k8s.io
