FROM docker.io/library/alpine:3.20
RUN apk add --no-cache tinyproxy socat
COPY tinyproxy.conf /etc/tinyproxy/tinyproxy.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && mkdir -p /var/log/tinyproxy
ENTRYPOINT ["/entrypoint.sh"]
